# Generated by Django 5.2.6 on 2025-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
