# Generated by Django 5.2.6 on 2025-09-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_token_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name_plural': 'Token'},
        ),
        migrations.RenameField(
            model_name='token',
            old_name='role',
            new_name='type',
        ),
    ]
