# Generated by Django 5.2.6 on 2025-09-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_token_options_rename_role_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('OTP', 'Otp'), ('FORGOT_PASSWORD', 'Forgot Password'), ('VERFIY_ACCOUNT', 'Verfiy Account')], default='OTP', max_length=20),
        ),
    ]
