# Generated by Django 5.2.6 on 2025-10-22 09:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('validate_till', models.DateTimeField()),
                ('stock', models.IntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], default='', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('available_stock', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_order_amount', models.FloatField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_per_user', models.IntegerField(default=1)),
                ('term_conditions', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('DEAL', 'DEAL'), ('COUPON', 'COUPON'), ('CASHBACK', 'CASHBACK')], default='COUPON', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('validate_till', models.DateTimeField()),
                ('stock', models.IntegerField(default=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], default='', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('available_stock', models.IntegerField(default=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_order_amount', models.FloatField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_per_user', models.IntegerField(default=1)),
                ('term_conditions', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('COUPON_EXPIRY', 'Coupon Expiry'), ('NEW_DEAL', 'New Deal'), ('PAYMENT', 'Payment')], default='NEW_DEAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('api', models.URLField()),
                ('api_key', models.CharField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, max_length=800, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Store',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
    ]
