# Generated by Django 5.2.6 on 2025-10-01 12:14

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('website_url', models.URLField(blank=True, max_length=800, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.ManyToManyField(to='coupon.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('COUPON_EXPIRY', 'Coupon Expiry'), ('NEW_DEAL', 'New Deal'), ('PAYMENT', 'Payment')], default='NEW_DEAL', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.store')),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='sub_category',
            field=models.ManyToManyField(to='coupon.subcategory'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.URLField(blank=True, max_length=800, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('orignal_price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_until', models.DateTimeField()),
                ('term_conditions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.store')),
                ('sub_category', models.ManyToManyField(to='coupon.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Deal',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('validate_till', models.DateTimeField()),
                ('stock', models.IntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('discount', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCTANGE', 'Perctange')], default='FLAT', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('available_stock', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_order_amount', models.FloatField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_per_user', models.IntegerField(default=1)),
                ('term_conditions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.store')),
                ('sub_category', models.ManyToManyField(to='coupon.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Coupon',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wishlist',
            },
        ),
    ]
