# Generated by Django 5.2.6 on 2025-09-29 12:13

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_merchant_banner_alter_merchant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.URLField(blank=True, max_length=800, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('orignal_price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_until', models.DateTimeField()),
                ('term_conditions', models.TextField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
