# Generated by Django 5.2.6 on 2025-09-29 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name_plural': 'Deal'},
        ),
        migrations.AlterModelOptions(
            name='merchant',
            options={'verbose_name_plural': 'Merchant'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.merchant')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Category',
            },
        ),
    ]
