# Generated by Django 5.2.6 on 2025-10-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(blank=True, choices=[('DEAL', 'Deal'), ('COUPON', 'Coupon'), ('GIFT_CARD', 'Gift Card'), ('CASHBACK', 'Cashback')], default='COUPON', max_length=20),
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
