# Generated by Django 5.2.6 on 2025-09-30 04:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_deal_options_alter_merchant_options_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Merchant',
            new_name='Store',
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name_plural': 'Store'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='merchant',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='merchant',
            new_name='store',
        ),
    ]
