# Generated by Django 5.2.6 on 2025-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon_type_delete_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(blank=True, choices=[('DEAL', 'DEAL'), ('COUPON', 'COUPON'), ('GIFT_CARD', 'GIFT_CARD'), ('CASHBACK', 'CASHBACK')], default='COUPON', max_length=20),
        ),
    ]
