# Generated by Django 5.2.6 on 2025-09-30 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_rename_merchant_store_alter_store_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('validate_till', models.DateTimeField()),
                ('stock', models.IntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('discount', models.CharField(max_length=50)),
                ('discount_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCTANGE', 'Perctange')], default='FLAT', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('available_stock', models.IntegerField(default=1)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('min_order_amount', models.FloatField(blank=True, null=True)),
                ('max_discount_amount', models.FloatField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(default=1)),
                ('usage_per_user', models.IntegerField(default=1)),
                ('term_conditions', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.store')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupon.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coupon',
            },
        ),
    ]
