# Generated by Django 5.2.6 on 2025-10-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_alter_notification_title_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
