# Generated by Django 5.2.6 on 2025-10-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0007_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('FLAT', 'Flat'), ('PERCTANGE', 'Perctange')], default='', max_length=20),
        ),
    ]
