# Generated by Django 5.2.6 on 2025-10-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='discount_applied',
        ),
    ]
